# Kanagawa Wave theme for Kitty

# The basic colors
foreground              #dcd7ba
background              #1f1f28
selection_foreground    #1f1f28
selection_background    #dcd7ba

# Cursor colors
cursor                  #dcd7ba
cursor_text_color       #1f1f28

# URL underline color when hovering with mouse
url_color               #7e9cd8

# Tab bar colors
active_tab_foreground   #1f1f28
active_tab_background   #dcd7ba
inactive_tab_foreground #dcd7ba
inactive_tab_background #54546d

# The 16 terminal colors

# black
color0 #090618
color8 #727169

# red
color1 #c34043
color9 #e82424

# green
color2  #76946a
color10 #98bb6c

# yellow
color3  #c0a36e
color11 #e6c384

# blue
color4  #7e9cd8
color12 #7fb4ca

# magenta
color5  #957fb8
color13 #938aa9

# cyan
color6  #6a9589
color14 #7aa89f

# white
color7  #c8c093
color15 #dcd7ba
