#!/usr/bin/env zsh

# Sync Bear notes to Astro blog and push to Netlify
BLOG_DIR=~/dev/danieldosen_org

cd "$BLOG_DIR" || exit 1

echo "$(date): Running blog sync..."

# Run the sync script
npm run sync

# Check if there are changes to commit
if [[ -n $(git status --porcelain) ]]; then
  echo "Changes detected, committing..."

  git add -A
  git commit -m "Sync posts from Bear

🤖 Auto-generated by blog_publish.sh"

  git push

  echo "$(date): Published to Netlify"
else
  echo "$(date): No changes to publish"
fi
