# Gruvbox Light colors for Alacritty

# Default colors
[colors.primary]
background = '#fbf1c7' # Light background
foreground = '#3c3836' # Dark foreground

# Cursor colors
[colors.cursor]
text = '#fbf1c7'
cursor = '#3c3836'

# Normal colors
[colors.normal]
black   = '#3c3836'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#9d0006'
green   = '#79740e'
yellow  = '#b57614'
blue    = '#076678'
magenta = '#8f3f71'
cyan    = '#427b58'
white   = '#fbf1c7'


