import= [
 # - ~/.config/alacritty/alacritty-colors.yaml
 # "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
 # - ~/.config/alacritty/themes/themes/gruvbox_light.yaml
 # - ~/.config/alacritty/themes/themes/gruvbox_material.yaml
 # - ~/.config/alacritty/themes/themes/tokyo-night.yaml
]
