# Gruvbox Light
# Default colors
# NOTE: This palette is based on the official Gruvbox light theme
[colors.primary]
foreground = '#3c3836'
background = '#fbf1c7'

# Normal colors
[colors.normal]
black   = '#fbf1c7'
red     = '#9d0006'
green   = '#79740e'
yellow  = '#b57614'
blue    = '#076678'
magenta = '#8f3f71'
cyan    = '#427b58'
white   = '#3c3836'

# Bright colors
[colors.bright]
black   = '#f9f5d7'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#282828'
